### ISSUE TITLE
weapons problem

### ISSUE THREAD

**Issue by Sully1796376** [Serrulata-Studios/serrulata-forgery-qb-#1]
dont get a weapon as store is saying somthing about license ive checked the police file its in there but police manually have to grant weapons license i dont no how to change this to make it work any help would be great thanks

**Comment by V0rt3xRP** [comment]
This script only gives a Item - nothing with changing database / characters main information.

**Comment by V0rt3xRP** [comment]
V2 will be a fully rewrite once we get time! You can join our discord and post a suggestion for what you would like to see!
